run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

linters-settings:
  staticcheck:
    checks:
      - all

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
